version: "3.9"

services:
  # TGJU Proxy Service (اول اجرا میشه)
  tgju_proxy:
    build:
      context: .
      dockerfile: Dockerfile
      target: tgju-proxy
    command: python services/tgju.py
    volumes:
      - .:/app
    ports:
      - "5001:5001"
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G

  # API Service (بعد از tgju_proxy اجرا میشه)
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    command: gunicorn --workers 2 --worker-class gevent --bind 0.0.0.0:5000 --timeout 600 "main:create_app()"
    ports:
      - "5000:5000"
    volumes:
      - ./services:/app/services
      - ./models:/app/models
      - ./config:/app/config
    depends_on:
      - tgju_proxy
    restart: always
    deploy:
      resources:
        limits:
          memory: 2G

  # Scheduler Service (فعلاً غیر فعال)
  # scheduler:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: scheduler
  #   command: python scheduler.py
  #   volumes:
  #     - .:/app
  #   restart: always
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 2G