"""Add weekly_growth and other fields to GoldenKeyResult

Revision ID: 0af8563a591e
Revises: 6617ccf27b66
Create Date: 2025-07-24 01:24:14.589616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0af8563a591e'
down_revision = '6617ccf27b66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('golden_key_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weekly_growth', sa.Float(), nullable=True, comment='Weekly growth percentage of the symbol'))

    with op.batch_alter_table('weekly_watchlist_results', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'active'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_watchlist_results', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'active'"))

    with op.batch_alter_table('golden_key_results', schema=None) as batch_op:
        batch_op.drop_column('weekly_growth')

    # ### end Alembic commands ###
