"""Add probability_percent to PotentialBuyQueueResult

Revision ID: 156358259c0d
Revises: 6b9b68612182
Create Date: 2025-07-25 19:48:52.959544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156358259c0d'
down_revision = '6b9b68612182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('potential_buy_queue_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('probability_percent', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('potential_buy_queue_results', schema=None) as batch_op:
        batch_op.drop_column('probability_percent')

    # ### end Alembic commands ###
