"""Add last_fundamental_update_date to ComprehensiveSymbolData

Revision ID: 6563d97fb84a
Revises: 24081f04ad40
Create Date: 2025-09-15 18:35:29.675205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6563d97fb84a'
down_revision = '24081f04ad40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comprehensive_symbol_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_fundamental_update_date', sa.Date(), nullable=True))

    with op.batch_alter_table('signals_performance', schema=None) as batch_op:
        batch_op.create_unique_constraint('_signal_id_uc', ['signal_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signals_performance', schema=None) as batch_op:
        batch_op.drop_constraint('_signal_id_uc', type_='unique')

    with op.batch_alter_table('comprehensive_symbol_data', schema=None) as batch_op:
        batch_op.drop_column('last_fundamental_update_date')

    # ### end Alembic commands ###
