"""Add performance tracking fields to WeeklyWatchlistResult

Revision ID: 6617ccf27b66
Revises: 71130349a2e6
Create Date: 2025-07-23 23:12:43.790518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6617ccf27b66'
down_revision = '71130349a2e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_watchlist_results', schema=None) as batch_op:
        # --- اصلاحات حیاتی برای ستون status ---
        # ابتدا ستون را به صورت nullable=True اضافه می‌کنیم
        # سپس یک مقدار پیش‌فرض سرور برای رکوردهای موجود تعیین می‌کنیم
        # و در نهایت (در یک مرحله جداگانه اگر نیاز بود) می‌توان آن را به NOT NULL تغییر داد.
        # برای سادگی، فعلا آن را nullable=True و با server_default نگه می‌داریم.
        batch_op.add_column(sa.Column('status', sa.String(50), nullable=True, server_default='active'))
        batch_op.add_column(sa.Column('exit_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('exit_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('jexit_date', sa.String(10), nullable=True))
        batch_op.add_column(sa.Column('profit_loss_percentage', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_watchlist_results', schema=None) as batch_op:
        batch_op.drop_column('profit_loss_percentage')
        batch_op.drop_column('jexit_date')
        batch_op.drop_column('exit_date')
        batch_op.drop_column('exit_price')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
