"""Add nullable status and probability_percent to GoldenKeyResult

Revision ID: 6b9b68612182
Revises: fc5133c9e18a
Create Date: 2025-07-25 12:42:53.868292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b9b68612182'
down_revision = 'fc5133c9e18a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('golden_key_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True, comment='Status of the signal (active, closed_profit, closed_loss, closed_neutral)'))
        batch_op.add_column(sa.Column('probability_percent', sa.Float(), nullable=True, comment='Estimated probability of success for this signal'))
        batch_op.drop_column('matched_filters')

    with op.batch_alter_table('signals_performance', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signals_performance', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('golden_key_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matched_filters', sa.INTEGER(), nullable=True))
        batch_op.drop_column('probability_percent')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
