"""Manual correction for MLPrediction symbol_id type and add outcome_evaluated_at

Revision ID: 70d8ef792c61
Revises: f529c6b88499
Create Date: 2025-07-28 08:15:02.255869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d8ef792c61'
down_revision = 'f529c6b88499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_predictions', schema=None) as batch_op:
        # اضافه کردن ستون outcome_evaluated_at
        # اگر این ستون قبلاً به صورت دستی در دیتابیس شما وجود نداشته باشد، این خط آن را اضافه می کند.
        # اگر مطمئن نیستید، می توانید قبل از اجرا، دیتابیس را با یک ابزار مانند DB Browser for SQLite چک کنید.
        # اگر ستون قبلا وجود دارد، این خط خطا می دهد.
        batch_op.add_column(sa.Column('outcome_evaluated_at', sa.DateTime(), nullable=True, comment="Timestamp when the actual outcome was evaluated"))

    # نکته: ما فعلاً symbol_id را تغییر نمی دهیم، چون شما ترجیح دادید آن را ثابت نگه دارید
    # و با توجه به اینکه گفتید برای بقیه کلاس ها هم همین شکل است.
    # اگر در آینده به دلیل Foreign Key به symbols.id مشکلی پیش آمد، باید به این موضوع برگردیم.

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_predictions', schema=None) as batch_op:
        # حذف ستون outcome_evaluated_at در صورت نیاز به بازگشت به نسخه قبلی
        batch_op.drop_column('outcome_evaluated_at')
    # ### end Alembic commands ###