"""Add any missing columns after stamping head

Revision ID: 71130349a2e6
Revises: 
Create Date: 2025-07-13 01:05:46.862476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71130349a2e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('golden_key_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matched_filters', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('golden_key_results', schema=None) as batch_op:
        batch_op.drop_column('matched_filters')

    # ### end Alembic commands ###
