"""Remove performance tracking columns and unique constraint from GoldenKeyResult

Revision ID: 8bc053675ae3
Revises: f04b3edcb93c
Create Date: 2025-10-09 21:35:31.720359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bc053675ae3'
down_revision = 'f04b3edcb93c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('golden_key_results', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('_symbol_jdate_golden_key_uc'), type_='unique')
        batch_op.drop_column('weekly_growth')
        batch_op.drop_column('probability_percent')
        batch_op.drop_column('final_price')
        batch_op.drop_column('profit_loss_percentage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('golden_key_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profit_loss_percentage', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('final_price', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('probability_percent', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('weekly_growth', sa.FLOAT(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('_symbol_jdate_golden_key_uc'), ['symbol_id', 'jdate'])

    # ### end Alembic commands ###
