"""Add tse_index to ComprehensiveSymbolData

Revision ID: 94df9d7ee10c
Revises: 
Create Date: 2025-09-13 03:03:39.422687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94df9d7ee10c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candlestick_pattern_detection', schema=None) as batch_op:
        batch_op.alter_column('symbol_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'comprehensive_symbol_data', ['symbol_id'], ['id'])

    with op.batch_alter_table('comprehensive_symbol_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tse_index', sa.String(length=20), nullable=False))

    with op.batch_alter_table('financial_ratios_data', schema=None) as batch_op:
        batch_op.alter_column('symbol_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'comprehensive_symbol_data', ['symbol_id'], ['id'])

    with op.batch_alter_table('fundamental_data', schema=None) as batch_op:
        batch_op.alter_column('symbol_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'comprehensive_symbol_data', ['symbol_id'], ['id'])

    with op.batch_alter_table('golden_key_results', schema=None) as batch_op:
        batch_op.alter_column('symbol_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'comprehensive_symbol_data', ['symbol_id'], ['id'])

    with op.batch_alter_table('ml_predictions', schema=None) as batch_op:
        batch_op.alter_column('symbol_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'comprehensive_symbol_data', ['symbol_id'], ['id'])

    with op.batch_alter_table('potential_buy_queue_results', schema=None) as batch_op:
        batch_op.alter_column('symbol_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'comprehensive_symbol_data', ['symbol_id'], ['id'])

    with op.batch_alter_table('sentiment_data', schema=None) as batch_op:
        batch_op.alter_column('symbol_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'comprehensive_symbol_data', ['symbol_id'], ['id'])

    with op.batch_alter_table('signals_performance', schema=None) as batch_op:
        batch_op.alter_column('symbol_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'comprehensive_symbol_data', ['symbol_id'], ['id'])

    with op.batch_alter_table('stock_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('symbol_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'comprehensive_symbol_data', ['symbol_id'], ['id'])

    with op.batch_alter_table('technical_indicator_data', schema=None) as batch_op:
        batch_op.alter_column('symbol_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'comprehensive_symbol_data', ['symbol_id'], ['id'])

    with op.batch_alter_table('tsetmc_filter_result', schema=None) as batch_op:
        batch_op.alter_column('symbol_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'comprehensive_symbol_data', ['symbol_id'], ['id'])

    with op.batch_alter_table('weekly_watchlist_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symbol_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'comprehensive_symbol_data', ['symbol_id'], ['id'])
        batch_op.drop_column('symbol')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_watchlist_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symbol', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('symbol_id')

    with op.batch_alter_table('tsetmc_filter_result', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'comprehensive_symbol_data', ['symbol_id'], ['symbol_id'])
        batch_op.alter_column('symbol_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('technical_indicator_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'comprehensive_symbol_data', ['symbol_id'], ['symbol_id'])
        batch_op.alter_column('symbol_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('stock_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('symbol_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('id')

    with op.batch_alter_table('signals_performance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'comprehensive_symbol_data', ['symbol_id'], ['symbol_id'])
        batch_op.alter_column('symbol_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('sentiment_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('symbol_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('potential_buy_queue_results', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('symbol_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('ml_predictions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'comprehensive_symbol_data', ['symbol_id'], ['symbol_id'])
        batch_op.alter_column('symbol_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('golden_key_results', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'comprehensive_symbol_data', ['symbol_id'], ['symbol_id'])
        batch_op.alter_column('symbol_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('fundamental_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'comprehensive_symbol_data', ['symbol_id'], ['symbol_id'])
        batch_op.alter_column('symbol_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('financial_ratios_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'comprehensive_symbol_data', ['symbol_id'], ['symbol_id'])
        batch_op.alter_column('symbol_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('comprehensive_symbol_data', schema=None) as batch_op:
        batch_op.drop_column('tse_index')

    with op.batch_alter_table('candlestick_pattern_detection', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'comprehensive_symbol_data', ['symbol_id'], ['symbol_id'])
        batch_op.alter_column('symbol_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
