"""Recreate alembic history

Revision ID: aee0f136615d
Revises: 
Create Date: 2025-09-23 14:39:44.514645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aee0f136615d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technical_indicator_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Stochastic_K', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('Stochastic_D', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('squeeze_on', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('halftrend_signal', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('resistance_level_50d', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('resistance_broken', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technical_indicator_data', schema=None) as batch_op:
        batch_op.drop_column('resistance_broken')
        batch_op.drop_column('resistance_level_50d')
        batch_op.drop_column('halftrend_signal')
        batch_op.drop_column('squeeze_on')
        batch_op.drop_column('Stochastic_D')
        batch_op.drop_column('Stochastic_K')

    # ### end Alembic commands ###
