"""Add DailySectorPerformance table

Revision ID: f04b3edcb93c
Revises: aee0f136615d
Create Date: 2025-10-08 02:55:24.602325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f04b3edcb93c'
down_revision = 'aee0f136615d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_sector_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jdate', sa.String(length=10), nullable=False),
    sa.Column('sector_name', sa.String(length=255), nullable=False),
    sa.Column('total_trade_value', sa.BigInteger(), nullable=True),
    sa.Column('net_money_flow', sa.BigInteger(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jdate', 'sector_name', name='uq_jdate_sector')
    )
    with op.batch_alter_table('daily_sector_performance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_sector_performance_jdate'), ['jdate'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_sector_performance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_sector_performance_jdate'))

    op.drop_table('daily_sector_performance')
    # ### end Alembic commands ###
