"""Add updated_at to SignalsPerformance

Revision ID: f529c6b88499
Revises: 156358259c0d
Create Date: 2025-07-25 21:53:46.227045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f529c6b88499'
down_revision = '156358259c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signals_performance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True, comment='زمان آخرین به\u200cروزرسانی رکورد'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signals_performance', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
