"""Add average profit/loss to AggregatedPerformance

Revision ID: fc5133c9e18a
Revises: <YOUR_NEW_REVISION_ID>
Create Date: 2025-07-24 11:55:13.156156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc5133c9e18a'
down_revision = '<YOUR_NEW_REVISION_ID>'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aggregated_performance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_profit_per_win', sa.Float(), nullable=False, comment='میانگین سود هر سیگنال موفق'))
        batch_op.add_column(sa.Column('average_loss_per_loss', sa.Float(), nullable=False, comment='میانگین زیان هر سیگنال ناموفق'))
        batch_op.add_column(sa.Column('net_profit_percent', sa.Float(), nullable=False, comment='درصد سود/زیان خالص (سود کل + زیان کل)'))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True, comment='زمان آخرین به\u200cروزرسانی رکورد'))
        batch_op.alter_column('total_signals',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('successful_signals',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('win_rate',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('total_profit_percent',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('total_loss_percent',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aggregated_performance', schema=None) as batch_op:
        batch_op.alter_column('total_loss_percent',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('total_profit_percent',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('win_rate',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('successful_signals',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_signals',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('net_profit_percent')
        batch_op.drop_column('average_loss_per_loss')
        batch_op.drop_column('average_profit_per_win')

    # ### end Alembic commands ###
